version: "3"
services:
  postgres-service:
    image: postgres:13.2
    restart: always
    container_name: "lm-tool-postgres"
    environment:
      - POSTGRES_DB=${ENV_POSTGRES_DB_NAME}
      - POSTGRES_USER=${ENV_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${ENV_POSTGRES_DB_PASSWORD}
    ports:
      - 127.0.0.1:${ENV_POSTGRES_DB_PORT}:5432
volumes:
  telsmart:
    driver: local
